// Mocks generated by Mockito 5.4.4 from annotations
// in kuwot/test/features/quote/presentation/bloc/quote_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:kuwot/core/data/local/config.dart' as _i12;
import 'package:kuwot/core/data/local/translation_target_config.dart' as _i13;
import 'package:kuwot/core/domain/no_params.dart' as _i11;
import 'package:kuwot/core/error/failure.dart' as _i5;
import 'package:kuwot/features/quote/domain/entities/background_image.dart'
    as _i10;
import 'package:kuwot/features/quote/domain/entities/quote.dart' as _i6;
import 'package:kuwot/features/quote/domain/use_cases/get_background_images.dart'
    as _i9;
import 'package:kuwot/features/quote/domain/use_cases/get_quote.dart' as _i2;
import 'package:kuwot/features/quote/domain/use_cases/get_translated_quote.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetQuote].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetQuote extends _i1.Mock implements _i2.GetQuote {
  MockGetQuote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Quote>> call(
          _i2.GetQuoteParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [params],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.Quote>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i6.Quote>>(
          this,
          Invocation.method(
            #execute,
            [params],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.Quote>>);
}

/// A class which mocks [GetTranslatedQuote].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTranslatedQuote extends _i1.Mock
    implements _i8.GetTranslatedQuote {
  MockGetTranslatedQuote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Quote>> call(
          _i8.GetTranslatedQuoteParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [params],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.Quote>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i6.Quote>>(
          this,
          Invocation.method(
            #execute,
            [params],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.Quote>>);
}

/// A class which mocks [GetBackgroundImages].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBackgroundImages extends _i1.Mock
    implements _i9.GetBackgroundImages {
  MockGetBackgroundImages() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i10.BackgroundImage>>> call(
          _i11.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [params],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, List<_i10.BackgroundImage>>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, List<_i10.BackgroundImage>>>(
          this,
          Invocation.method(
            #execute,
            [params],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i10.BackgroundImage>>>);
}

/// A class which mocks [Config].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranslationTargetConfig extends _i1.Mock
    implements _i12.Config<_i13.TranslationTarget> {
  MockTranslationTargetConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i13.TranslationTarget?> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _i3.Future<_i13.TranslationTarget?>.value(),
      ) as _i3.Future<_i13.TranslationTarget?>);

  @override
  _i3.Future<void> set(_i13.TranslationTarget? value) => (super.noSuchMethod(
        Invocation.method(
          #set,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> remove() => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
