workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 30
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'dev'
          include: true
          source: false
    environment:
      android_signing:
        - dhemasnurjaya_keystore
      groups:
        - app_secrets
        - google_play_credentials
      vars:
        PACKAGE_NAME: "com.dhemasnurjaya.kuwot"
        GOOGLE_PLAY_TRACK: "alpha"
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: false
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          BUILD_NAME="1.1.$BUILD_NUMBER"

          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV
          echo "BUILD_NAME=$BUILD_NAME" >> $CM_ENV

          flutter build appbundle --release \
            --dart-define=QUOTE_API_SCHEME=$QUOTE_API_SCHEME \
            --dart-define=QUOTE_API_HOST=$QUOTE_API_HOST \
            --dart-define=AUTH_PUBLIC_KEY=$AUTH_PUBLIC_KEY \
            --dart-define=SENTRY_DSN=$SENTRY_DSN \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
    success:
      scripts:
        - name: Set correct release name on Google Play
          script: |
            google-play releases edit \
              --package-name "$PACKAGE_NAME" \
              --track "$GOOGLE_PLAY_TRACK" \
              --version-code "$BUILD_NUMBER" \
              --release-name "$BUILD_NAME"
