// Mocks generated by Mockito 5.4.4 from annotations
// in kuwot/test/features/quote/data/repositories/quote_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kuwot/features/quote/data/data_sources/remote/pexels_api_remote_data_source.dart'
    as _i6;
import 'package:kuwot/features/quote/data/data_sources/remote/quote_api_remote_data_source.dart'
    as _i4;
import 'package:kuwot/features/quote/data/models/photo_list_model.dart' as _i3;
import 'package:kuwot/features/quote/data/models/quote_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQuoteModel_0 extends _i1.SmartFake implements _i2.QuoteModel {
  _FakeQuoteModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePhotoListModel_1 extends _i1.SmartFake
    implements _i3.PhotoListModel {
  _FakePhotoListModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuoteApiRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuoteApiRemoteDataSource extends _i1.Mock
    implements _i4.QuoteApiRemoteDataSource {
  MockQuoteApiRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.QuoteModel> getQuote({String? query}) => (super.noSuchMethod(
        Invocation.method(
          #getQuote,
          [],
          {#query: query},
        ),
        returnValue: _i5.Future<_i2.QuoteModel>.value(_FakeQuoteModel_0(
          this,
          Invocation.method(
            #getQuote,
            [],
            {#query: query},
          ),
        )),
      ) as _i5.Future<_i2.QuoteModel>);

  @override
  _i5.Future<_i2.QuoteModel> getTranslatedQuote(
    int? id, {
    String? query,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslatedQuote,
          [id],
          {#query: query},
        ),
        returnValue: _i5.Future<_i2.QuoteModel>.value(_FakeQuoteModel_0(
          this,
          Invocation.method(
            #getTranslatedQuote,
            [id],
            {#query: query},
          ),
        )),
      ) as _i5.Future<_i2.QuoteModel>);
}

/// A class which mocks [PexelsApiRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPexelsApiRemoteDataSource extends _i1.Mock
    implements _i6.PexelsApiRemoteDataSource {
  MockPexelsApiRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.PhotoListModel> getCuratedPhotos() => (super.noSuchMethod(
        Invocation.method(
          #getCuratedPhotos,
          [],
        ),
        returnValue: _i5.Future<_i3.PhotoListModel>.value(_FakePhotoListModel_1(
          this,
          Invocation.method(
            #getCuratedPhotos,
            [],
          ),
        )),
      ) as _i5.Future<_i3.PhotoListModel>);
}
